# Generated by Django 3.0.4 on 2020-03-16 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cofferupApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contributorcoffertransaction',
            name='is_contribution',
        ),
        migrations.AddField(
            model_name='contributorcoffer',
            name='is_settled',
            field=models.BooleanField(default=0),
        ),
    ]
