# Generated by Django 3.0.4 on 2020-03-25 19:07

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cofferupApp', '0002_auto_20200316_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributor',
            name='avatar',
            field=cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='avatar'),
        ),
    ]
