# Generated by Django 3.0.4 on 2020-03-25 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cofferupApp', '0003_contributor_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contributor',
            name='avatar',
        ),
        migrations.AddField(
            model_name='contributor',
            name='image_url',
            field=models.URLField(default=''),
        ),
    ]
